version: '3.8'

services:
  pg:
    image: postgres:15
    container_name: shahzoda-pg
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1
    ports:
    - '5432:5432'
    volumes:
    - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: shahzoda-web
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - pg

volumes:
  pg_data:
