# Generated by Django 5.1.4 on 2024-12-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('program', models.CharField(choices=[('graduate', 'Graduate'), ('undergraduate', 'Undergraduate'), ('continuing', 'Continuing'), ('community_music', 'CommunityMusic')], max_length=255)),
                ('session', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=255)),
                ('year', models.IntegerField()),
                ('hour', models.IntegerField(default=3)),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('campus', models.CharField(default='Webster Univ Tashkent Uzbekistan', max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('days', models.CharField(choices=[('m', 'M'), ('tu', 'Tu'), ('w', 'W'), ('th', 'Th'), ('f', 'F'), ('s', 'S')], default='m', max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_semester', models.DateField()),
                ('end_semester', models.DateField()),
                ('tm', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], max_length=50)),
            ],
        ),
    ]
